version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: jpedrodp/burger_builder:dev
    ports:
      - "80:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
